'use client';
import {useState,type FormEvent} from 'react';
import useSWR from 'swr';
import {api,send,errorText} from '@/lib/api';
import {useAuth} from '@/components/provider';
import {PageHeading,Loading,ErrorBox,Empty,FormModal} from '@/components/ui';
import {Icon} from '@/components/icons';
import type {Dashboard,Device} from '@/lib/types';
export default function DevicesPage(){
 const {user}=useAuth(),{data:devices,error,mutate}=useSWR<Device[]>('/devices',api),{data}=useSWR<Dashboard>('/dashboard',api,{refreshInterval:15000});
 const [edit,setEdit]=useState<Device|'new'|null>(null),[formError,setFormError]=useState(''),[busy,setBusy]=useState(false);
 const manage=user?.role==='ADMIN'||user?.role==='MANAGER',existing=edit&&edit!=='new'?edit:null;
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setFormError('');const f=new FormData(e.currentTarget);
 try{await send(edit==='new'?'/devices':'/devices/'+existing?.id,{name:f.get('name'),areaId:f.get('areaId')||null,...(edit==='new'?{id:f.get('id'),type:f.get('type')}: {})},edit==='new'?'POST':'PATCH');setEdit(null);await mutate();}catch(e){setFormError(errorText(e));}finally{setBusy(false);}}
 return <><PageHeading eyebrow="СЕНСОРНАЯ СЕТЬ" title="Два датчика. Полная картина." description="Регистрируйте устройства по MQTT ID и назначайте лесным участкам." action={manage&&<button className="button primary" onClick={()=>{setEdit('new');setFormError('');}}><Icon name="plus" size={17}/>Добавить датчик</button>}/>
 <div className="sensor-intro-grid"><div className="sensor-intro"><div className="sensor-visual hmp"><span/><span/><span/><span/></div><div><span className="eyebrow">МИКРОКЛИМАТ</span><h2>Vaisala HMP155</h2><p>Температура −80…+60 °C<br/>Относительная влажность 0–100 %</p></div><Icon name="temp" size={32}/></div><div className="sensor-intro"><div className="sensor-visual fs"><span/></div><div><span className="eyebrow">ПРИЗНАКИ ВОЗГОРАНИЯ</span><h2>Honeywell FS24X</h2><p>Многоспектральный детектор пламени<br/>Сигнал тревоги и состояние неисправности</p></div><Icon name="flame" size={32}/></div></div>
 <ErrorBox message={error?.message}/>{!devices&&!error?<Loading/>:devices?.length?<div className="panel table-scroll"><table><thead><tr><th>Датчик</th><th>Тип</th><th>Лесной участок</th><th>MQTT topic</th><th>Состояние</th>{manage&&<th/>}</tr></thead><tbody>{devices.map(d=>{const live=data?.areas.flatMap(a=>a.devices).find(x=>x.id===d.id)?.lastReading;const online=live&&new Date(data?.serverTime??0).getTime()-new Date(live.measuredAt).getTime()<120000;return <tr key={d.id}><td><b>{d.name}</b><small className="table-sub">{d.id}</small></td><td><span className="subtle-tag">{d.type}</span></td><td>{d.area?.name||<span className="muted">Не назначен</span>}</td><td><code className="topic">firewatch/nodes/{d.id}/telemetry</code></td><td><span className={'device-status '+(online&&!live?.fault?'ok':'')}><i/>{!d.areaId?'Без участка':live?.fault?'Неисправность':online?'На связи':'Нет данных'}</span></td>{manage&&<td><button className="button small secondary" onClick={()=>{setEdit(d);setFormError('');}}>Настроить</button></td>}</tr>;})}</tbody></table></div>:<Empty title="Датчики ещё не зарегистрированы" text="Добавьте устройство с тем же ID, который оно передаёт в MQTT."/>}
 <div className="info-note"><Icon name="sensor"/><p>На одном участке можно назначить один HMP155 и один FS24X. Новый датчик начинает участвовать в расчёте после первого сообщения. Переназначение сохраняет историю прежнего участка.</p></div>
 {edit&&<FormModal title={edit==='new'?'Регистрация датчика':'Настройка датчика'} onClose={()=>setEdit(null)}><form onSubmit={save}>{edit==='new'&&<><label>MQTT ID<input name="id" required pattern="[a-zA-Z0-9_-]{1,80}" placeholder="burabay-hmp155" autoFocus/><small>Латинские буквы, цифры, дефис и подчёркивание.</small></label><label>Тип датчика<select name="type"><option value="HMP155">Vaisala HMP155 · температура и влажность</option><option value="FS24X">Honeywell FS24X · пламя</option></select></label></>}<label>Название<input name="name" required minLength={2} maxLength={100} defaultValue={existing?.name} placeholder="Датчик у северной границы"/></label><label>Лесной участок<select name="areaId" defaultValue={existing?.areaId??''}><option value="">Не назначен</option>{data?.areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><ErrorBox message={formError}/><button className="button primary full" disabled={busy}>{busy?'Сохранение…':'Сохранить датчик'}</button></form></FormModal>}
 </>;
}
