'use client';
import Link from 'next/link';
import {useParams} from 'next/navigation';
import useSWR from 'swr';
import {api,formatTime} from '@/lib/api';
import type {Detail} from '@/lib/types';
import {PageHeading,Loading,ErrorBox,Badge,RiskGauge} from '@/components/ui';
import {Icon} from '@/components/icons';
import {Chart} from '@/components/chart';
export default function AreaPage(){
 const {id}=useParams<{id:string}>(),{data:area,error}=useSWR<Detail>('/areas/'+id,api,{refreshInterval:15000});
 if(error)return <ErrorBox message={error.message}/>;if(!area)return <Loading/>;
 const r=area.risk;
 return <><Link className="back-link" href="/areas">← Все лесные участки</Link><PageHeading eyebrow="МОНИТОРИНГ УЧАСТКА" title={area.name} description={area.location+' · '+area.hectares+' га · '+area.lat.toFixed(4)+', '+area.lng.toFixed(4)} action={<Badge level={r.level}/>}/>
 {r.simulated&&<div className="demo-strip"><span className="status-dot"/><b>Симулятор</b><span>Учебный поток данных, не реальные измерения леса.</span></div>}
 <div className="detail-top"><section className="panel risk-panel"><div className="section-heading"><h2>Объединённая оценка</h2><span className="subtle-tag">{r.version}</span></div><div className="risk-summary"><RiskGauge risk={r}/><div><Badge level={r.level}/><h3>{r.quality==='COMPLETE'?'Оба датчика доступны':r.quality==='PARTIAL'?'Неполные данные':'Данные устарели'}</h3><p>{r.forecast===null?'Прогноз появится после накопления истории.':'Тенденция на 5 минут: '+r.forecast+'/100'}</p><small className="muted">Индекс риска, не вероятность пожара.</small></div></div><div className="reasons">{r.reasons.length?r.reasons.map(x=><p key={x}><span/> {x}</p>):<p><span/>Параметры в пределах базового сценария</p>}</div></section>
 <section className="panel"><div className="section-heading"><h2>Что влияет на риск</h2><Link className="text-link" href="/methodology">Методика ↗</Link></div><div className="contributions">{r.contributions.map(c=><div key={c.label}><div><span>{c.label}</span><b>{c.value.toFixed(1)} <small>/ {c.max}</small></b></div><div className="contribution-track"><i style={{width:(c.value/c.max*100)+'%'}}/></div></div>)}</div><p className="muted tiny">При обнаружении пламени итоговый индекс поднимается минимум до 90. Удержание тревоги может сохранять уровень при снижении индекса.</p></section></div>
 <div className="metric-grid">{[{icon:'temp',name:'Температура',value:r.temperatureC?.toFixed(1)??'—',unit:'°C',sub:'Vaisala HMP155',rate:r.temperatureRate},{icon:'drop',name:'Влажность',value:r.humidityPct?.toFixed(1)??'—',unit:'%',sub:'Vaisala HMP155',rate:r.humidityRate},{icon:'flame',name:'Признаки пламени',value:r.flameDetected===null?'Нет данных':r.flameDetected?'Обнаружены':'Не обнаружены',unit:'',sub:'Honeywell FS24X',rate:null}].map(m=><section className="panel metric-card" key={m.name}><span className="metric-label"><Icon name={m.icon}/>{m.name}</span><strong>{m.value}<small>{m.unit}</small></strong><div className="card-bottom"><span>{m.sub}</span>{m.rate!==null&&<span>{m.rate>0?'+':''}{m.rate.toFixed(2)} {m.unit}/мин</span>}</div></section>)}</div>
 <div className="charts-grid"><section className="panel"><h2>Температура и её динамика</h2><Chart label="Температура" unit="°C" points={area.history.map(h=>({date:h.createdAt,value:h.result.temperatureC}))}/></section><section className="panel"><h2>Относительная влажность</h2><Chart label="Влажность" unit="%" color="#0891B2" points={area.history.map(h=>({date:h.createdAt,value:h.result.humidityPct}))}/></section><section className="panel"><h2>История риска</h2><Chart label="Риск" unit="/100" color="#DC2626" points={area.history.map(h=>({date:h.createdAt,value:h.score}))}/></section><section className="panel"><h2>Подключённые датчики</h2>{area.devices.map(d=><div className="detail-device" key={d.id}><Icon name="sensor"/><div><b>{d.name}</b><small>{d.id}</small><small>{formatTime(d.lastReading?.measuredAt)}</small></div><span className="subtle-tag">{d.type}</span></div>)}{!area.devices.length&&<p className="muted">Датчики пока не назначены.</p>}<Link className="text-link" href="/devices">Управлять датчиками <Icon name="arrow" size={16}/></Link><p className="muted tiny">{area.description}</p></section></div>
 <section className="panel section-space"><div className="section-heading"><h2>Последние измерения</h2><span className="subtle-tag">MQTT → PostgreSQL</span></div><div className="table-scroll"><table><thead><tr><th>Время</th><th>Датчик</th><th>Температура</th><th>Влажность</th><th>Пламя</th><th>Источник</th></tr></thead><tbody>{area.readings.slice(0,20).map(s=><tr key={s.id}><td>{formatTime(s.measuredAt)}</td><td>{s.deviceId}</td><td>{s.temperatureC===null?'—':s.temperatureC+' °C'}</td><td>{s.humidityPct===null?'—':s.humidityPct+' %'}</td><td>{s.fault?'Неисправность':s.flameDetected===null?'—':s.flameDetected?'Да':'Нет'}</td><td>{s.simulated?'Симулятор':'Датчик'}</td></tr>)}</tbody></table>{!area.readings.length&&<p className="muted">Ожидаем первое измерение.</p>}</div></section>
 </>;
}
